### ISSUE TITLE
Segfault with remove() after accessing an attribute

### ISSUE THREAD

**Issue by hildjj** [polotek/libxmljs#308]
Consider the following code, run with `node --expose-gc`:

```js
// This isn't used.
// Hypothesis: load up the runtime enough to cause a GC.
// Comment it out to see success.
// If this doesn't fail on your machine, try adding more libraries.
var https = require('https');

var xml = require('libxmljs');
var doc = xml.parseXml("<foo><bar baz='t'/></foo>");
var b = doc.get('bar');
b.attr('baz');
b.remove();
setImmediate(gc);
```

In the garbage collection routine (`gc`), node crashes with a segmentation fault.  GDB shows the backtrace as:

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0xffffffffffffffff
0x0000000102acd560 in libxmljs::XmlNode::~XmlNode (this=0x100b1a680) at ../src/xml_node.cc:194
194	    XmlDocument* doc = static_cast<XmlDocument*>(xml_obj->doc->_private);
(gdb) where
#0  0x0000000102acd560 in libxmljs::XmlNode::~XmlNode (this=0x100b1a680) at ../src/xml_node.cc:194
#1  0x0000000102ac5aae in libxmljs::XmlAttribute::~XmlAttribute (this=0x100b1a680) at xml_attribute.h:11
#2  0x0000000102ac5a24 in node::ObjectWrap::WeakCallback (data=<value temporarily unavailable, due to optimizations>) at node_object_wrap.h:129
#3  0x00000001001f27de in v8::internal::GlobalHandles::Node::PostGarbageCollectionProcessing ()
#4  0x00000001001f1a90 in v8::internal::GlobalHandles::PostGarbageCollectionProcessing ()
#5  0x00000001002055a4 in v8::internal::Heap::PerformGarbageCollection ()
#6  0x00000001002051a9 in v8::internal::Heap::CollectGarbage ()
...
```

As you can see, the XmlAttribute destructor for the removed element is trying to free the XmlDocument a second time. When a node is removed, there likely needs to be more cleanup than what is currently in XmlNode.cc:

```C++
void
XmlNode::remove() {
  xmlUnlinkNode(xml_obj);
}

NAN_METHOD(XmlNode::Remove) {
  NanScope();
  XmlNode *node = ObjectWrap::Unwrap<XmlNode>(args.Holder());
  assert(node);

  node->remove();

  NanReturnValue(args.Holder());
}
```

I don't yet understand enough about the internals of your C++ layer to suggest a fix.

OS: OSX 10.10.3
Node: v0.12.2 (from homebrew)

**Comment by hildjj** [comment]
This is a dup of #163
