### ISSUE TITLE
Does not run on 0.12.2

### ISSUE THREAD

**Issue by Rauno56** [polotek/libxmljs#312]
After npm install and `require('libxmljs')` I get following:
```
Error: /pathtoproject/node_modules/libxmljs/build/Release/xmljs.node: undefined symbol: _ZN2v82V837AdjustAmountOfExternalAllocatedMemoryEl
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/pathtoproject/node_modules/libxmljs/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/pathtoproject/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
Seems to be OK on 0.10.36.

**Comment by defunctzombie** [comment]
Why don't you please share some things you tried to do to debug this?

**Comment by rkrishnan2012** [comment]
remove the node_modules folder and re-run the npm install.

**Comment by Rauno56** [comment]
Nope. Still not working. I didn't really debug this. I have a script:
```
console.log('VER', process.version);
require('libxmljs');
console.log('OK');
```
and locally installed(npm version 2.10.1, which comes with node 12.x). Running the script with 12.x yields error, 10.x does not.

If you tell me that it works with your 12.x installation, the only reason I can see this happening is that install process does not play well with non-globally installed node binaries(node in my path is 10.x, to test 12.x I've separate binaries). I'm on debian linux.

**Comment by Rauno56** [comment]
Feeling about the build process seems to be right. Changing 12.x to be in my path instead of the 10.x did install and work correctly. Thanks.
