### ISSUE TITLE
Error: Could not parse XML string

### ISSUE THREAD

**Issue by KamaZz** [polotek/libxmljs#329]
When I trying to parse this page, I've got an error:
```
/var/parsing/node_modules/libxmljs/lib/document.js:139
    return bindings.fromHtml(string, opts);
                    ^
Error: Could not parse XML string
    at Error (native)
    at Object.module.exports.fromHtml (/var/parsing/node_modules/libxmljs/lib/document.js:139:21)
    at parsePage (/var/parsing/militarist.js:41:22)
    at /var/parsing/militarist.js:115:15
    at IncomingMessage.<anonymous> (/var/parsing/militarist.js:93:4)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Can I somehow ignore this error or fix it?

**Comment by KamaZz** [comment]
That's my fail, thank you.
